### ISSUE TITLE
separate configuration file?

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#1]
Currently, a few key configuration parameters are set in the Makefile:
1. The base IRI for the compiled ontology.
2. The term source files and the order in which to parse them.

Might it be better to have a separate configuration file for these items, and anything else that might arise?

**Comment by ramonawalls** [comment]
Guess it depends on how hard it is to edit the Makefile without messing it up.

**Comment by stuckyb** [comment]
With the move to the new, pure Python build system, the Makefile is obsolete and configuration settings are now in a separate config file, as described in the original question.  So I guess the answer was "yes".  :-)
