### ISSUE TITLE
alternative module extraction methods

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#14]
Currently, module extraction only uses SyntacticLocalityModuleExtractor, but it might be useful to implement other methods.  E.g., single term extraction, or something that more closely approximates the output of OntoFox.

**Comment by ramonawalls** [comment]
+1

**Comment by stuckyb** [comment]
I now realize that we will probably need alternatives for the PPO to avoid an ontology that is too difficult to reason over, so I am making this feature a priority.

**Comment by stuckyb** [comment]
I've implemented a completely new framework for module extraction and a new set of entity extraction algorithms that provide an alternative to SyntacticLocalityModuleExtractor.  The new extraction methods are very flexible and give users fine-grained control over what components of an ontology should be included in an import module.  In testing on the PPO, they can also produce modules that perform far faster in reasoning tasks than do corresponding SyntacticLocalityModuleExtractor modules.  I think this issue can be considered closed.
