### ISSUE TITLE
build an ontology with no terms, only imports

### ISSUE THREAD

**Issue by ramonawalls** [stuckyb/ontobuilder#29]
Is this possible? When I try it, I get the following error:

make: *** No rule to make target `/Users/rwalls-iplant/ppo_ingest_app/src/terms/piao_term_definitions.csv', needed by `pdiao.owl'.  Stop.

but I'm not sure if this is because I don't have a piao_terms_definitions file or because of some other issue.

**Comment by ramonawalls** [comment]
Oh, never mind. I do have a file there. Looking into other issues now.

**Comment by stuckyb** [comment]
I actually don't think it was possible with the old, Make-based build system, but after reading @ramonawalls comment, I realized this might be useful in some cases.  So the new build system explicitly supports building ontologies with no terms.
