### ISSUE TITLE
auto-generate new project

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#33]
It would be a very useful feature (I think) if the build system were able to automatically generate a new project with a single command.  This would include the project folder structure, configuration file, base ontology, and initial top-level imports CSV file.

**Comment by jdeck88** [comment]
+1 on this feature!

**Comment by stuckyb** [comment]
Thanks for the +1, @jdeck88.  This feature is implemented now.  Initializing a new project creates a complete ontology project with sample imports and terms definitions that will compile into a working OWL ontology file.
