### ISSUE TITLE
build/release file and IRI management

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#44]
I am working on finalizing a sensible (default) file and IRI management scheme, and I'd appreciate some feedback on a few questions.  Here they are, in no particular order.

1. What files should be included in a release?  The options would be a "plain" ontology file (not pre-reasoned, imports not merged), a pre-reasoned ontology file, a "merged" ontology file (imports merged), or a pre-reasoned and merged ontology file.

2. How should those files be named?  Specifically, which file should get the "simple" name (e.g., ppo.owl)?  How should the others be named?  Examples: ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc.

3. Should releases use an explicit folder structure?  In this scenario, creating a new release would mean creating a new folder, something like "./releases/2017-02-15/", and then placing the generated files inside the folder.  The other option would be to depend entirely on tags in the version control system.  The problem with the tag option is that it makes older releases much harder to access (from the repository, anyway).  E.g., there is no easy way to pull down a specific file from a tagged commit on GitHub.  Getting the ontology file from an old release would require either downloading the tag tarball and extracting the file or cloning the repository and checking out a new branch initialized at the tag point.  Neither is trivial for someone who doesn't have decent working knowledge of git and/or GitHub.  With the explicit folder system, getting previous ontology releases is very easy.

4. How should IRIs be managed?  I've looked at some repositories for other ontology projects, and at least one approach is to give all variations of an ontology file the same IRI, but give each a separate version IRI.  So, ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc. would all have the same IRI, but each would get a unique version IRI.  Is that an acceptable solution?  Should some or all of these files actually have different IRIs besides just the version IRI?

I have looked at how OORT handles some of these.  OORT uses the explicit folder structure solution for 3.  For 2 and 4, OORT seems to make a number of assumptions about file names, formats, and source organization, and I'd like to avoid those assumptions, if possible.

I need to sort all of this out in order to close out several remaining issue tickets.  I also want to refactor part of the main executable and build system to make it more modular, and that will also require working out some of these details.  These are all "community of practice" sorts of questions without clear objective best answers, so I didn't want to answer them on my own.

**Comment by robgur** [comment]
Brian, comments, finally, below:

What files should be included in a release? The options would be a "plain" ontology file (not pre-reasoned, imports not merged), a pre-reasoned ontology file, a "merged" ontology file (imports merged), or a pre-reasoned and merged ontology file.

RPG: I am not sure.  It seems the cost is low to include pre-reasoned and merged ontology files?

How should those files be named? Specifically, which file should get the "simple" name (e.g., ppo.owl)? How should the others be named? Examples: ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc.

RPG:  I think simple is the ppo.owl file, yes.  I am good with the suggestion to use underscores or dashes for how other files are provisioned e.g. ppo_reasoned.owl.

Should releases use an explicit folder structure? In this scenario, creating a new release would mean creating a new folder, something like "./releases/2017-02-15/", and then placing the generated files inside the folder. The other option would be to depend entirely on tags in the version control system.  

RPG: I lean strongly towards an explicit folder structure.

How should IRIs be managed? I've looked at some repositories for other ontology projects, and at least one approach is to give all variations of an ontology file the same IRI, but give each a separate version IRI. So, ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc. would all have the same IRI, but each would get a unique version IRI. Is that an acceptable solution? Should some or all of these files actually have different IRIs besides just the version IRI?

RPG: I think the solution you suggest is fine e.g separate version IRIs.

I need to sort all of this out in order to close out several remaining issue tickets. I also want to refactor part of the main executable and build system to make it more modular, and that will also require working out some of these details. These are all "community of practice" sorts of questions without clear objective best answers, so I didn't want to answer them on my own.

RPG: I am not sure this helps, but hope so?

**Comment by ramonawalls** [comment]
Brian, sorry for the delay. The last week has been pretty crazy.

1. What files should be included in a release? The options would be a "plain" ontology file (not pre-reasoned, imports not merged), a pre-reasoned ontology file, a "merged" ontology file (imports merged), or a pre-reasoned and merged ontology file.

This is something that will vary from project to project, so you may want to make it so the tool can release the full set, but people don't have to use them all. Here is the full list of files that I think should be included in a release, if you really want analyses that use the release reproducible:
-All of the files that are used to build the ontology (most of these can just be part of a tag of the repo)
-An unmerged, unreasoned version of the ontology, equivalent to the editors version, but tagged for the release.
-A merged, unreasoned version of the ontology.
-A merged, prereasoned version of the ontology.

The last one is what becomes the official ontology release - what the main PURL points to.

2.  How should those files be named? Specifically, which file should get the "simple" name (e.g., ppo.owl)? How should the others be named? Examples: ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc.

There aren't any real standards for this, but the following names are widely used (using PPO as an example):
ppo-edit.owl - The editors version (unmerged, unreasoned), and the one we work on day to day.
ppo-merged.owl - The merged but unreasoned version
ppo.owl - The merged, prereasoned version for release.

Perhaps if an annotation is added to the ontology file at release specifying which one it is, the names will be less important.

3.  Should releases use an explicit folder structure? In this scenario, creating a new release would mean creating a new folder, something like "./releases/2017-02-15/", and then placing the generated files inside the folder. The other option would be to depend entirely on tags in the version control system. The problem with the tag option is that it makes older releases much harder to access (from the repository, anyway). E.g., there is no easy way to pull down a specific file from a tagged commit on GitHub. Getting the ontology file from an old release would require either downloading the tag tarball and extracting the file or cloning the repository and checking out a new branch initialized at the tag point. Neither is trivial for someone who doesn't have decent working knowledge of git and/or GitHub. With the explicit folder system, getting previous ontology releases is very easy.

I've used both ways and don't have a strong preference. For tagged versions, you can actually go right to the ontology file by including the tag in the URL. In fact, that is how I make version specific PURLs. It's true that it is harder to get the whole package that way. If it is easy for you to generate a release specific folder, then I concur with Rob on this.

4.  How should IRIs be managed? I've looked at some repositories for other ontology projects, and at least one approach is to give all variations of an ontology file the same IRI, but give each a separate version IRI. So, ppo-reasoned.owl, ppo-merged-reasoned.owl, ppo-unreasoned.owl, etc. would all have the same IRI, but each would get a unique version IRI. Is that an acceptable solution? Should some or all of these files actually have different IRIs besides just the version IRI?

The more or less standard practice is to use the same IRI for each version of the ontology but then create a specific version IRI. Based on the names I suggested in question 2, we would have three IRIs that are the same as their PURLs:

http://purl.obolibrary.org/obo/ppo/ppo-edit.owl
http://purl.obolibrary.org/obo/ppo/ppo-merged.owl
http://purl.obolibrary.org/obo/ppo.owl 

Note that the last one is a slightly different format from the others, as per OBO convention, with no /ppo in the string.

If we did a release on Feb. 22, 2017 for these files, the version IRIs would be:

http://purl.obolibrary.org/obo/ppo/releases/2017-02-22/ppo-edit.owl
http://purl.obolibrary.org/obo/ppo/releases/2017-02-22/ppo-merged.owl
http://purl.obolibrary.org/obo/ppo/releases/2017-02-22/ppo.owl 

Note that for the version IRI of the main file, the IRI and PURL include the extra /ppo in the string.

**Comment by stuckyb** [comment]
Thanks, all, for giving me feedback on these questions.  Ramona, thank you for the very detailed guidelines.

So, I've had some time to think through implementation, and here is what I propose:

### Configuration file
The project configuration file will include 3 settings:
1. `dev_base_IRI`: A base IRI for the compiled, non-released ontology documents.  The base IRI can be either a folder on the local filesystem or a folder at a remote location (e.g., GitHub repository).
2. `release_base_IRI`: A base IRI for ontology releases.  This would typically be the root of the PURL for the ontology (e.g., "http://purl.obolibrary.org/obo/ppo/").  If undefined, defaults to `dev_base_IRI`.
3. `release_ontology_IRI`: A full IRI for the main ontology document, if it needs to be different from the pattern of `release_base_IRI`.  If undefined, will simply follow the pattern of `release_base_IRI`.

### Imports compilation
All import modules will be assigned IRIs generated as:
`dev_base_IRI + "imports/module_name.owl"`

(Note that actual IRI generation will use smart path merging, not just simple string concatenation.)

### Non-release ontology compilation
For non-release ontology compilation, the IRIs of the various ontology documents will be automatically generated using the value of `dev_base_IRI`.  File names and IRIs will be generated as follows (using ppo as an example):
1. `dev_base_IRI + "ontology/ppo-basic.owl"`: The unmerged, unreasoned ontology.
2. `dev_base_IRI + "ontology/ppo-merged.owl"`: The merged, unreasoned ontology.
3. `dev_base_IRI + "ontology/ppo-reasoned.owl"`: The pre-reasoned ontology.
4. `dev_base_IRI + "ontology/ppo-merged-reasoned.owl"`: The merged, pre-reasoned ontology.

Note that in 1), I am deliberately not using "ppo-edit.owl".  In the context of ontobuilder, that name would be misleading, because the compiled ontology document should generally *not* be edited directly.

### Release compilation
For a release ontology compilation, the IRIs of the various ontology documents will be automatically generated using the values of `release_base_IRI` and `release_ontology_IRI` (if provided).  File names and IRIs will be generated as follows:
1. `(release_ontology_IRI) OR (release_base_IRI + "ppo.owl")`: The merged, pre-reasoned ontology.
2. `release_base_IRI + "ppo-basic.owl"`:  The unmerged, unreasoned ontology.
3. `release_base_IRI + "ppo-merged.owl"`:  The merged, unreasoned ontology.

Version IRIs will be generated as follows:
1. `release_base_IRI + "releases/YYYY-MM-DD/ppo.owl"`
2. `release_base_IRI + "releases/YYYY-MM-DD/ppo-basic.owl"`
3. `release_base_IRI + "releases/YYYY-MM-DD/ppo-merged.owl"`

Released import modules file names and IRIs will be generated as:
`release_base_IRI + "imports/module_name.owl"`
And the import modules version IRIs will be:
`release_base_IRI + "releases/YYYY-MM-DD/imports/module_name.owl"`

So, what am I forgetting?  What are the must-have special cases that will cause this plan to fail?  Finally, an important question: What about the name "ppo-basic.owl" as an alternative to "ppo-edit.owl"?  Would something else be better?

**Comment by ramonawalls** [comment]
Brian, this is great. I cannot think of any special cases that will cause this to fail, but admittedly, I am a bit sleep deprived. 

Regarding ppo-basic.owl, I fully agree with your reasoning for not using ppo-edit, but I'm afraid basic suggests something else to me (e.g., a simple view of ppo that only includes, say, ppo classes with no imports - something that might actually be useful to include). How about ppo-raw or ppo-work?

**Comment by stuckyb** [comment]
Thanks, @ramonawalls.  I agree with your point about the name "basic".  "Raw" might be the best choice; I've not thought of anything else I like better.

**Comment by stuckyb** [comment]
Okay, this is now all implemented as described!

One other question:  Would we want source files to be included in a release?  My inclination is to say "no" -- source code could/should be managed with version control system tags.  Other thoughts?

**Comment by ramonawalls** [comment]
Agree no re. the source files as part of the release.

**Comment by stuckyb** [comment]
Rob confirmed that he agrees with @ramonawalls and me on this question, so that means that this feature is complete and this issue can be closed.
