### ISSUE TITLE
'imported from' annotations

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#60]
Should we add IAO 'imported from' annotations to all entities in import modules?

**Comment by ramonawalls** [comment]
I would say yes. This is particularly helpful if you import a term from an ontology that has a different namespace (e.g., a relation from RO that has a BFO id). You wouldn't want this if you are importing a whole ontology directly, only if you are making a new ontology to import that is a subset of the source.

**Comment by stuckyb** [comment]
Done, I think.

Here's how it works: If imports are merged into the main ontology, then each imported entity will get an 'imported from' annotation to indicate its original source.  If imports are confined to separate OWL files (i.e., import modules), then the entities will not be annotated because in that case, the entire import module has a single annotation indicating the original source, so there is no need to annotate the entities individually.

@ramonawalls, does that strategy make sense?  Also, this is all configurable in the settings file, so that merged entity annotations can be disabled if there is a reason to do so.

**Comment by ramonawalls** [comment]
This sounds great, Brian.

------------------------------------------------------
Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by stuckyb** [comment]
Okay, great -- closing this, then.
