### ISSUE TITLE
generate base ontology

### ISSUE THREAD

**Issue by stuckyb** [stuckyb/ontobuilder#8]
It should be possible to automatically generate a base ontology using information gathered from the Makefile.  This would be a useful feature that would further simplify developing new ontologies.  The feature would also be useful for automatically adding new import modules to the base ontology.

**Comment by ramonawalls** [comment]
I like this feature.

**Comment by stuckyb** [comment]
Getting closer here.  The build system now supports automatic management of import statements in the compiled ontology so that import modules do not have to be added by hand.  The next step will be automatically generating the initial base ontology.

**Comment by stuckyb** [comment]
This feature is fully implemented now with the addition of support for automatic creation and initialization of new ontology projects.
