### ISSUE TITLE
unmodified init fails to make on windows

### ISSUE THREAD

**Issue by ehunsinger** [stuckyb/ontobuilder#92]
See image
![ontopiloterror](https://user-images.githubusercontent.com/38735909/39333730-ca210e4a-4960-11e8-899b-b00af6603099.jpg)

**Comment by stuckyb** [comment]
Thanks for reporting this.  I will have a look ASAP...

**Comment by stuckyb** [comment]
I confirmed the bug on a Windows test machine.  I should have time to investigate this further by the end of the week or early next.

**Comment by stuckyb** [comment]
Fixed with the latest commit.
